import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import LoadingComponent from "@/components/LoadingBar";
import Providers from "./providers";
import StoreProvider from "./StoreProvider";
//Components
import Topbar from "@/components/topbar";
import Header from "@/components/header";
import Footer from "@/components/footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <StoreProvider>
            <Topbar />
            <Header />
            {children ? children : <LoadingComponent />}
            <Footer />
          </StoreProvider>
        </Providers>
      </body>
    </html>
  );
}
